plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
logo: https://raw.githubusercontent.com/dsckiet/resources/master/dsckiet-logo.png

theme: jekyll-theme-minimal
